# (c) https://github.com/MontiCore/monticore

image: maven:3.5.4-jdk-11

stages:
  - build
  - deploy

before_script:
  - chmod +x gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle


build:
  stage: build
  script:
    - "./gradlew build $GRADLE_OPT $ARGS1"
    
deploy:
  stage: deploy
  script:
    - "./gradlew publish -PmavenPassword=$pass -PmavenUser=$user $GRADLE_OPT $ARGS2"